# Generated by Django 3.2.13 on 2022-06-22 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='pai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='escola.pai'),
        ),
    ]
